SPECIALITIES = [
    ('Addiction Psychiatrist', 'Addiction Psychiatrist'),
    ('Adolescent Medicine Specialist', 'Adolescent Medicine Specialist'),
    ('Allergist/Immunologist', 'Allergist/Immunologist'),
    ('Anatomic Pathologist', 'Anatomic Pathologist'),
    ('Anesthesiologist', 'Anesthesiologist'),
    ('Audiologist', 'Audiologist'),
    ('Bariatric Physician', 'Bariatric Physician'),
    ('Cardiac Electrophysiologist', 'Cardiac Electrophysiologist'),
    ('Cardiologist', 'Cardiologist'),
    ('Cardiothoracic Surgeon', 'Cardiothoracic Surgeon'),
    ('Certified Nurse Midwife (CNM)', 'Certified Nurse Midwife (CNM)'),
    ('Child Psychiatrist', 'Child Psychiatrist'),
    ('Chiropractor', 'Chiropractor'),
    ('Clinical Biochemical Geneticist', 'Clinical Biochemical Geneticist'),
    ('Clinical Cytogeneticist', 'Clinical Cytogeneticist'),
    ('Clinical Geneticist', 'Clinical Geneticist'),
    ('Clinical Immunologist', 'Clinical Immunologist'),
    ('Clinical Microbiologist', 'Clinical Microbiologist'),
    ('Clinical Molecular Geneticist', 'Clinical Molecular Geneticist'),
    ('Clinical Pathologist', 'Clinical Pathologist'),
    ('Clinical Pharmacologist', 'Clinical Pharmacologist'),
    ('Colorectal Surgeon', 'Colorectal Surgeon'),
    ('Critical Care Medicine Specialist', 'Critical Care Medicine Specialist'),
    ('Dermatologist', 'Dermatologist'),
    ('Developmental-Behavioral Pediatrician', 'Developmental-Behavioral Pediatrician'),
    ('Diagnostic Radiologist', 'Diagnostic Radiologist'),
    ('Ear, Nose & Throat Doctor (ENT/Otolaryngologist)', 'Ear, Nose & Throat Doctor (ENT/Otolaryngologist)'),
    ('Electrophysiologist', 'Electrophysiologist'),
    ('Emergency Medicine Physician', 'Emergency Medicine Physician'),
    ('Endocrinologist', 'Endocrinologist'),
    ('Family Medicine Physician', 'Family Medicine Physician'),
    ('Forensic Pathologist', 'Forensic Pathologist'),
    ('Gastroenterologist', 'Gastroenterologist'),
    ('General Practice Physician', 'General Practice Physician'),
    ('General Surgeon', 'General Surgeon'),
    ('Geriatric Medicine Specialist', 'Geriatric Medicine Specialist'),
    ('Geriatric Psychiatrist', 'Geriatric Psychiatrist'),
    ('Gynecologic Oncologist', 'Gynecologic Oncologist'),
    ('Hand Surgeon', 'Hand Surgeon'),
    ('Hematologist', 'Hematologist'),
    ('Hematopathologist', 'Hematopathologist'),
    ('Hepatologist', 'Hepatologist'),
    ('Hospitalist', 'Hospitalist'),
    ('Infectious Disease Specialist', 'Infectious Disease Specialist'),
    ('Integrative Medicine Physician', 'Integrative Medicine Physician'),
    ('Interventional Cardiologist', 'Interventional Cardiologist'),
    ('Interventional Radiologist', 'Interventional Radiologist'),
    ('Medical Geneticist', 'Medical Geneticist'),
    ('Medical Microbiologist', 'Medical Microbiologist'),
    ('Medical Oncologist', 'Medical Oncologist'),
    ('Neonatal-Perinatal Medicine Specialist', 'Neonatal-Perinatal Medicine Specialist'),
    ('Nephrologist', 'Nephrologist'),
    ('Neurodevelopmental Disabilities Specialist', 'Neurodevelopmental Disabilities Specialist'),
    ('Neurologist', 'Neurologist'),
    ('Neuropathologist', 'Neuropathologist'),
    ('Neuropsychiatrist', 'Neuropsychiatrist'),
    ('Neurosurgeon', 'Neurosurgeon'),
    ('Nuclear Medicine Physician', 'Nuclear Medicine Physician'),
    ('Nurse Practitioner', 'Nurse Practitioner'),
    ('Obstetrician/Gynecologist (OB/GYN)', 'Obstetrician/Gynecologist (OB/GYN)'),
    ('Occupational Medicine Specialist', 'Occupational Medicine Specialist'),
    ('Occupational Therapist', 'Occupational Therapist'),
    ('Oncologist', 'Oncologist'),
    ('Ophthalmologist', 'Ophthalmologist'),
    ('Oral and Maxillofacial Surgeon', 'Oral and Maxillofacial Surgeon'),
    ('Orthodontist', 'Orthodontist'),
    ('Orthopedic Surgeon', 'Orthopedic Surgeon'),
    ('Osteopathic Manipulative Medicine Specialist', 'Osteopathic Manipulative Medicine Specialist'),
    ('Otolaryngologist (ENT)', 'Otolaryngologist (ENT)'),
    ('Pain Management Specialist', 'Pain Management Specialist'),
    ('Palliative Care Specialist', 'Palliative Care Specialist'),
    ('Pathologist', 'Pathologist'),
    ('Pediatric Allergist', 'Pediatric Allergist'),
    ('Pediatric Cardiologist', 'Pediatric Cardiologist'),
    ('Pediatric Critical Care Medicine Specialist', 'Pediatric Critical Care Medicine Specialist'),
    ('Pediatric Dermatologist', 'Pediatric Dermatologist'),
    ('Pediatric Emergency Medicine Specialist', 'Pediatric Emergency Medicine Specialist'),
    ('Pediatric Endocrinologist', 'Pediatric Endocrinologist'),
    ('Pediatric Gastroenterologist', 'Pediatric Gastroenterologist'),
    ('Pediatric Hematologist-Oncologist', 'Pediatric Hematologist-Oncologist'),
    ('Pediatric Infectious Disease Specialist', 'Pediatric Infectious Disease Specialist'),
    ('Pediatric Nephrologist', 'Pediatric Nephrologist'),
    ('Pediatric Neurologist', 'Pediatric Neurologist'),
    ('Pediatric Neurosurgeon', 'Pediatric Neurosurgeon'),
    ('Pediatric Ophthalmologist', 'Pediatric Ophthalmologist'),
    ('Pediatric Orthopedic Surgeon', 'Pediatric Orthopedic Surgeon'),
    ('Pediatric Otolaryngologist', 'Pediatric Otolaryngologist'),
    ('Pediatric Pathologist', 'Pediatric Pathologist'),
    ('Pediatric Pulmonologist', 'Pediatric Pulmonologist'),
    ('Pediatric Radiologist', 'Pediatric Radiologist'),
    ('Pediatric Rheumatologist', 'Pediatric Rheumatologist'),
    ('Pediatric Surgeon', 'Pediatric Surgeon'),
    ('Pediatric Urologist', 'Pediatric Urologist'),
    ('Pediatrician', 'Pediatrician'),
    ('Perinatologist', 'Perinatologist'),
    ('Physical Medicine and Rehabilitation Specialist (Physiatrist)', 'Physical Medicine and Rehabilitation Specialist (Physiatrist)'),
    ('Physical Therapist', 'Physical Therapist'),
    ('Physician Assistant', 'Physician Assistant'),
    ('Plastic Surgeon', 'Plastic Surgeon'),
    ('Podiatrist', 'Podiatrist'),
    ('Preventive Medicine Specialist', 'Preventive Medicine Specialist'),
    ('Prosthodontist', 'Prosthodontist'),
    ('Psychiatrist', 'Psychiatrist'),
    ('Psychoanalyst', 'Psychoanalyst'),
    ('Psychologist', 'Psychologist'),
    ('Pulmonologist', 'Pulmonologist'),
    ('Radiation Oncologist', 'Radiation Oncologist'),
    ('Radiologist', 'Radiologist'),
    ('Reproductive Endocrinologist', 'Reproductive Endocrinologist'),
    ('Rheumatologist', 'Rheumatologist'),
    ('Sleep Medicine Specialist', 'Sleep Medicine Specialist'),
    ('Sports Medicine Physician', 'Sports Medicine Physician'),
    ('Surgeon', 'Surgeon'),
    ('Surgical Oncologist', 'Surgical Oncologist'),
    ('Thoracic Surgeon', 'Thoracic Surgeon'),
    ('Urologist', 'Urologist'),
    ('Vascular Surgeon', 'Vascular Surgeon'),
]